/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package linter;

import java.io.*;
import java.io.InputStream;
import java.io.IOException;
import java.util.regex.Pattern;

public class App {

    public static void main(String[] args) throws IOException {

        String textLine = "";

        File file = new File("/home/sufianhamdan/java-fundamentals/linter/app/src/main/resources/gates.js");
        FileInputStream fis = null;
        String allContent = "";
        try {
            fis = new FileInputStream(file);
            System.out.println("Total file size to read (in bytes): " + fis.available());
            int content;
            while ((content = fis.read()) != -1) {
                // System.out.print((char) content);
                textLine += (char) content;
                String eachLine = textLine;

            }

            // String text = "This is the text to be searched " + "for occurrences of the pattern.";

            String pattern = "(?:L of .*?)(?:\\n|$)";

            boolean matches = Pattern.matches(pattern, textLine);
            System.out.println(textLine);

            System.out.println("matches = " + matches);
            // System.out.print(allContent);
            // Pattern patternL = Pattern.compile("(?:L of .*?)(?:\\n|$)",
            // Pattern.eachLine);
            System.out.print(allContent);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (fis != null)
                    fis.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }
}
